In [2]:
import numpy as np

In [3]:
benimListem = [30,40,50]
np.array(benimListem)



array([30, 40, 50])

In [4]:
matrixListesi = [[10,20,30],[40,50,60],[70,80,90]]
np.array(matrixListesi).T

array([[10, 40, 70],
       [20, 50, 80],
       [30, 60, 90]])

## Arange

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Zeros

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

## Ones

In [8]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Linspace

In [9]:
np.linspace(0,100,9)

array([  0. ,  12.5,  25. ,  37.5,  50. ,  62.5,  75. ,  87.5, 100. ])

## Eye

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random

In [11]:
np.random.randn(8,8)

array([[-0.18044619, -0.54757608,  1.12513403, -0.82555045,  0.30726003,
        -0.32443385,  0.89010412,  0.01733932],
       [ 1.24685948, -1.44397291, -0.09129044,  0.58647464,  0.61724375,
         0.66443952, -0.53475073, -0.9506465 ],
       [-0.96004605,  1.52724849,  1.66266551, -1.92355353, -0.14836349,
         2.42758579,  0.71235572,  0.13553173],
       [ 0.17230446, -1.54547795, -0.1384786 , -0.77421259, -0.06487749,
        -1.72224673, -0.0070687 ,  1.32518858],
       [-0.16466919,  1.08489188,  2.27687618, -0.92642783,  0.31857383,
         1.52167514, -1.62769973, -0.62585736],
       [-0.08281215,  0.25208403,  0.31098048, -0.92688207,  0.05578174,
         0.96086653,  0.54560605,  1.44746475],
       [ 0.77302452,  1.54187784,  0.77083407,  1.23050766, -0.14359481,
         0.81429249,  0.64706018,  1.08604885],
       [-0.27898507,  0.0916884 ,  0.8120088 , -0.77210631,  1.56263578,
         1.30042771,  0.38138039, -0.95150811]])

In [12]:
np.random.randint(0,10)

3

In [13]:
np.random.randint(0,10,7)

array([3, 7, 5, 5, 6, 3, 7])

In [14]:
np.random.randint(0,10,(8,8))

array([[9, 7, 0, 8, 0, 5, 1, 4],
       [9, 0, 9, 2, 8, 6, 1, 6],
       [9, 8, 6, 4, 7, 7, 0, 8],
       [6, 3, 4, 5, 9, 7, 8, 6],
       [4, 2, 8, 1, 9, 2, 3, 7],
       [9, 4, 0, 3, 0, 8, 6, 6],
       [5, 1, 2, 8, 4, 7, 8, 8],
       [7, 6, 3, 1, 6, 5, 6, 1]])

In [15]:
x = np.random.randint(0,11,(7,7))
x

array([[ 9,  8,  9,  2,  3,  5,  4],
       [ 1,  3,  4,  1, 10,  5,  4],
       [ 9,  3,  6,  6,  2,  5,  6],
       [ 1,  0, 10,  1,  7,  3,  2],
       [ 9,  5, 10,  2,  2,  9,  0],
       [ 9,  7,  1,  4,  6,  9,  7],
       [ 5,  8,  5,  3,  9,  1,  3]])

## Numpy Dizi Metodları

In [16]:
benimNumpyDizim = np.random.randint(0,100,30)
benimNumpyDizim

array([25,  7, 96, 80, 94, 94, 21, 44, 65, 92, 40, 38,  4, 44, 77, 50, 12,
       60, 92, 52, 55, 21, 93, 39, 97, 90, 15, 23, 36,  8])

In [17]:
x = benimNumpyDizim.reshape(6,5)
x

array([[25,  7, 96, 80, 94],
       [94, 21, 44, 65, 92],
       [40, 38,  4, 44, 77],
       [50, 12, 60, 92, 52],
       [55, 21, 93, 39, 97],
       [90, 15, 23, 36,  8]])

In [18]:
benimNumpyDizim.max()

97

In [19]:
x.argmax()

24

In [20]:
x.argmin()

12

In [21]:
x.shape

(6, 5)

## Numpy Dizi İndexler

In [22]:
benimDizim = np.arange(0,15)
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
benimDizim[5]

5

In [24]:
benimDizim[3:5]

array([3, 4])

In [25]:
benimDizim[3:8]=0
benimDizim

array([ 0,  1,  2,  0,  0,  0,  0,  0,  8,  9, 10, 11, 12, 13, 14])

In [26]:
yeniDizi = np.arange(0,100,5)
yeniDizi

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [27]:
slicing = yeniDizi[3:7]
slicing

array([15, 20, 25, 30])

In [28]:
slicing[0:]=30
slicing

array([30, 30, 30, 30])

In [29]:
yeniDizi

array([ 0,  5, 10, 30, 30, 30, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [30]:
ornekDizi = np.arange(0,24)
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [31]:
yeniornekDizi = ornekDizi.copy()
yeniornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [32]:
ornekdizislicing = yeniornekDizi[11:17]
ornekdizislicing[:] = 11

In [33]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [34]:
yeniornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 11, 11, 11, 11, 11,
       17, 18, 19, 20, 21, 22, 23])

## Numpy Matrix Indexleri

In [35]:
ornekmatrixdizisi = [[10,20,30],[40,50,60],[70,80,90]]
np.array(ornekmatrixdizisi)


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [39]:
yenidizi = np.array([10,20,30,40,50,60,70,80,90])
yenimatrix = yenidizi.reshape(3,3)

In [41]:
yenimatrix.shape

(3, 3)

In [44]:
yenimatrix[2]

array([70, 80, 90])

In [45]:
yenimatrix[0][1]

20

In [46]:
yenimatrix[0,2]

30

In [47]:
yenimatrix[1:,2]

array([60, 90])

In [48]:
yenimatrix[0:,0]

array([10, 40, 70])

In [49]:
yenimatrix[0:,1]

array([20, 50, 80])

In [50]:
yenimatrix[1,2:]

array([60])

In [51]:
yenimatrix[1,1:]

array([50, 60])

In [53]:
yeniliste = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]]
newmatrix = np.array(yeniliste)
newmatrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [55]:
newmatrix[[0,2,4]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

## Operasyonlar 

In [61]:
newsequence = np.random.randint(0,100,20)
newsequence

array([13, 56, 59,  9, 48, 57, 63, 79, 41, 26, 49, 69, 93, 85, 57, 37, 13,
       94, 11, 39])

In [62]:
newsequence > 11

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True])

In [63]:
conclusion = newsequence >= 17

In [64]:
conclusion

array([False,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True])

In [65]:
newsequence[conclusion]

array([56, 59, 48, 57, 63, 79, 41, 26, 49, 69, 93, 85, 57, 37, 94, 39])

In [67]:
sondizi = np.arange(0,17)
sondizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [68]:
sondizi + sondizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])